// Copyright (c) 2018, the IFMLEdit project authors. Please see the
// AUTHORS file for details. All rights reserved. Use of this source code is
// governed by the MIT license that can be found in the LICENSE file.
/*jslint node: true, nomen: true */
/*globals BASE_PATH */
"use strict";

exports.patterns = [
  {
    category: "Content Modification",
    list: [
      {id: "notification", title: 'Notification', type: 'content-modification', image: 'patterns/ifml7.png', description: 'Semper vitae litora quis est dui potenti nisi vel. Faucibus nisl sagittis ac mauris id ullamcorper vel morbi nec ridiculus litora sodales. Velit pretium ultricies penatibus. Facilisi natoque ultricies sapien ornare montes quis. Porta aliquet, ridiculus rhoncus varius magna congue volutpat litora et? Auctor integer neque turpis molestie mollis! Facilisis erat eget habitant suscipit, facilisi eget. Sociosqu conubia leo ullamcorper, rutrum sodales eu per. Habitant in per bibendum aptent maecenas euismod fames conubia vehicula. In senectus bibendum mollis imperdiet venenatis malesuada ligula tempor curabitur. Nascetur metus aptent parturient conubia! Vel morbi hendrerit eget rutrum amet per. Semper ullamcorper.'},
      {id: "cascaded-deletion", title: 'Cascaded Deletion', type: 'content-modification', image: 'patterns/ifml9.png', description: 'Semper vitae litora quis est dui potenti nisi vel. Faucibus nisl sagittis ac mauris id ullamcorper vel morbi nec ridiculus litora sodales. Velit pretium ultricies penatibus. Facilisi natoque ultricies sapien ornare montes quis. Porta aliquet, ridiculus rhoncus varius magna congue volutpat litora et? Auctor integer neque turpis molestie mollis! Facilisis erat eget habitant suscipit, facilisi eget. Sociosqu conubia leo ullamcorper, rutrum sodales eu per. Habitant in per bibendum aptent maecenas euismod fames conubia vehicula. In senectus bibendum mollis imperdiet venenatis malesuada ligula tempor curabitur. Nascetur metus aptent parturient conubia! Vel morbi hendrerit eget rutrum amet per. Semper ullamcorper.'},
      {id: "object-modification", title: 'Object Modification', type: 'content-modification', image: 'patterns/ifml10.png', description: 'Semper vitae litora quis est dui potenti nisi vel. Faucibus nisl sagittis ac mauris id ullamcorper vel morbi nec ridiculus litora sodales. Velit pretium ultricies penatibus. Facilisi natoque ultricies sapien ornare montes quis. Porta aliquet, ridiculus rhoncus varius magna congue volutpat litora et? Auctor integer neque turpis molestie mollis! Facilisis erat eget habitant suscipit, facilisi eget. Sociosqu conubia leo ullamcorper, rutrum sodales eu per. Habitant in per bibendum aptent maecenas euismod fames conubia vehicula. In senectus bibendum mollis imperdiet venenatis malesuada ligula tempor curabitur. Nascetur metus aptent parturient conubia! Vel morbi hendrerit eget rutrum amet per. Semper ullamcorper.'}
    ]
  },
  {
    category: "Content Navigation",
    list: [
      {id: "breadcrumbs", title: 'Breadcrumbs', type: 'content-navigation', image: 'patterns/ifml3.png', description: 'Semper vitae litora quis est dui potenti nisi vel. Faucibus nisl sagittis ac mauris id ullamcorper vel morbi nec ridiculus litora sodales. Velit pretium ultricies penatibus. Facilisi natoque ultricies sapien ornare montes quis. Porta aliquet, ridiculus rhoncus varius magna congue volutpat litora et? Auctor integer neque turpis molestie mollis! Facilisis erat eget habitant suscipit, facilisi eget. Sociosqu conubia leo ullamcorper, rutrum sodales eu per. Habitant in per bibendum aptent maecenas euismod fames conubia vehicula. In senectus bibendum mollis imperdiet venenatis malesuada ligula tempor curabitur. Nascetur metus aptent parturient conubia! Vel morbi hendrerit eget rutrum amet per. Semper ullamcorper.'},
      {id: "paging", title: 'Paging', type: 'content-navigation', image: 'patterns/ifml6.png', description: 'Semper vitae litora quis est dui potenti nisi vel. Faucibus nisl sagittis ac mauris id ullamcorper vel morbi nec ridiculus litora sodales. Velit pretium ultricies penatibus. Facilisi natoque ultricies sapien ornare montes quis. Porta aliquet, ridiculus rhoncus varius magna congue volutpat litora et? Auctor integer neque turpis molestie mollis! Facilisis erat eget habitant suscipit, facilisi eget. Sociosqu conubia leo ullamcorper, rutrum sodales eu per. Habitant in per bibendum aptent maecenas euismod fames conubia vehicula. In senectus bibendum mollis imperdiet venenatis malesuada ligula tempor curabitur. Nascetur metus aptent parturient conubia! Vel morbi hendrerit eget rutrum amet per. Semper ullamcorper.'},
      {id: "collection-preview", title: 'Collection Preview', type: 'content-navigation', image: 'patterns/ifml2.png', description: 'Semper vitae litora quis est dui potenti nisi vel. Faucibus nisl sagittis ac mauris id ullamcorper vel morbi nec ridiculus litora sodales. Velit pretium ultricies penatibus. Facilisi natoque ultricies sapien ornare montes quis. Porta aliquet, ridiculus rhoncus varius magna congue volutpat litora et? Auctor integer neque turpis molestie mollis! Facilisis erat eget habitant suscipit, facilisi eget. Sociosqu conubia leo ullamcorper, rutrum sodales eu per. Habitant in per bibendum aptent maecenas euismod fames conubia vehicula. In senectus bibendum mollis imperdiet venenatis malesuada ligula tempor curabitur. Nascetur metus aptent parturient conubia! Vel morbi hendrerit eget rutrum amet per. Semper ullamcorper.'},
      {id: "single-object-toolbar", title: 'Single Object Toolbar', type: 'content-navigation', image: 'patterns/ifml7.png', description: 'Semper vitae litora quis est dui potenti nisi vel. Faucibus nisl sagittis ac mauris id ullamcorper vel morbi nec ridiculus litora sodales. Velit pretium ultricies penatibus. Facilisi natoque ultricies sapien ornare montes quis. Porta aliquet, ridiculus rhoncus varius magna congue volutpat litora et? Auctor integer neque turpis molestie mollis! Facilisis erat eget habitant suscipit, facilisi eget. Sociosqu conubia leo ullamcorper, rutrum sodales eu per. Habitant in per bibendum aptent maecenas euismod fames conubia vehicula. In senectus bibendum mollis imperdiet venenatis malesuada ligula tempor curabitur. Nascetur metus aptent parturient conubia! Vel morbi hendrerit eget rutrum amet per. Semper ullamcorper.'},
      {id: "multistep-commands", title: 'Multistep Commands', type: 'content-navigation', image: 'patterns/ifml8.png', description: 'Semper vitae litora quis est dui potenti nisi vel. Faucibus nisl sagittis ac mauris id ullamcorper vel morbi nec ridiculus litora sodales. Velit pretium ultricies penatibus. Facilisi natoque ultricies sapien ornare montes quis. Porta aliquet, ridiculus rhoncus varius magna congue volutpat litora et? Auctor integer neque turpis molestie mollis! Facilisis erat eget habitant suscipit, facilisi eget. Sociosqu conubia leo ullamcorper, rutrum sodales eu per. Habitant in per bibendum aptent maecenas euismod fames conubia vehicula. In senectus bibendum mollis imperdiet venenatis malesuada ligula tempor curabitur. Nascetur metus aptent parturient conubia! Vel morbi hendrerit eget rutrum amet per. Semper ullamcorper.'},
      {id: "up-navigation", title: 'Up Navigation', type: 'content-navigation', image: 'patterns/ifml8-multi-page.png', description: 'Semper vitae litora quis est dui potenti nisi vel. Faucibus nisl sagittis ac mauris id ullamcorper vel morbi nec ridiculus litora sodales. Velit pretium ultricies penatibus. Facilisi natoque ultricies sapien ornare montes quis. Porta aliquet, ridiculus rhoncus varius magna congue volutpat litora et? Auctor integer neque turpis molestie mollis! Facilisis erat eget habitant suscipit, facilisi eget. Sociosqu conubia leo ullamcorper, rutrum sodales eu per. Habitant in per bibendum aptent maecenas euismod fames conubia vehicula. In senectus bibendum mollis imperdiet venenatis malesuada ligula tempor curabitur. Nascetur metus aptent parturient conubia! Vel morbi hendrerit eget rutrum amet per. Semper ullamcorper.'},
      {id: "back-navigation", title: 'Back Navigation', type: 'content-navigation', image: 'patterns/ifml9.png', description: 'Semper vitae litora quis est dui potenti nisi vel. Faucibus nisl sagittis ac mauris id ullamcorper vel morbi nec ridiculus litora sodales. Velit pretium ultricies penatibus. Facilisi natoque ultricies sapien ornare montes quis. Porta aliquet, ridiculus rhoncus varius magna congue volutpat litora et? Auctor integer neque turpis molestie mollis! Facilisis erat eget habitant suscipit, facilisi eget. Sociosqu conubia leo ullamcorper, rutrum sodales eu per. Habitant in per bibendum aptent maecenas euismod fames conubia vehicula. In senectus bibendum mollis imperdiet venenatis malesuada ligula tempor curabitur. Nascetur metus aptent parturient conubia! Vel morbi hendrerit eget rutrum amet per. Semper ullamcorper.'},
    ]
  },
  {
    category: "Content Search",
    list: [
      {id: "basic-search", title: 'Basic Search', type: 'content-search', image: 'patterns/ifml8.png', description: 'Semper vitae litora quis est dui potenti nisi vel. Faucibus nisl sagittis ac mauris id ullamcorper vel morbi nec ridiculus litora sodales. Velit pretium ultricies penatibus. Facilisi natoque ultricies sapien ornare montes quis. Porta aliquet, ridiculus rhoncus varius magna congue volutpat litora et? Auctor integer neque turpis molestie mollis! Facilisis erat eget habitant suscipit, facilisi eget. Sociosqu conubia leo ullamcorper, rutrum sodales eu per. Habitant in per bibendum aptent maecenas euismod fames conubia vehicula. In senectus bibendum mollis imperdiet venenatis malesuada ligula tempor curabitur. Nascetur metus aptent parturient conubia! Vel morbi hendrerit eget rutrum amet per. Semper ullamcorper.'},
    ]
  },
  {
    category: "Data Entry",
    list: [
      {id: "wizard", title: 'Wizard', type: 'data-entry', image: 'patterns/ifml2.png', description: 'Semper vitae litora quis est dui potenti nisi vel. Faucibus nisl sagittis ac mauris id ullamcorper vel morbi nec ridiculus litora sodales. Velit pretium ultricies penatibus. Facilisi natoque ultricies sapien ornare montes quis. Porta aliquet, ridiculus rhoncus varius magna congue volutpat litora et? Auctor integer neque turpis molestie mollis! Facilisis erat eget habitant suscipit, facilisi eget. Sociosqu conubia leo ullamcorper, rutrum sodales eu per. Habitant in per bibendum aptent maecenas euismod fames conubia vehicula. In senectus bibendum mollis imperdiet venenatis malesuada ligula tempor curabitur. Nascetur metus aptent parturient conubia! Vel morbi hendrerit eget rutrum amet per. Semper ullamcorper.'},
      {id: "multifield-forms", title: 'Multifield Forms', type: 'data-entry', image: 'patterns/ifml3.png', description: 'Semper vitae litora quis est dui potenti nisi vel. Faucibus nisl sagittis ac mauris id ullamcorper vel morbi nec ridiculus litora sodales. Velit pretium ultricies penatibus. Facilisi natoque ultricies sapien ornare montes quis. Porta aliquet, ridiculus rhoncus varius magna congue volutpat litora et? Auctor integer neque turpis molestie mollis! Facilisis erat eget habitant suscipit, facilisi eget. Sociosqu conubia leo ullamcorper, rutrum sodales eu per. Habitant in per bibendum aptent maecenas euismod fames conubia vehicula. In senectus bibendum mollis imperdiet venenatis malesuada ligula tempor curabitur. Nascetur metus aptent parturient conubia! Vel morbi hendrerit eget rutrum amet per. Semper ullamcorper.'},
      {id: "data-lookup", title: 'Data Lookup', type: 'data-entry', image: 'patterns/ifml4.png', description: 'Semper vitae litora quis est dui potenti nisi vel. Faucibus nisl sagittis ac mauris id ullamcorper vel morbi nec ridiculus litora sodales. Velit pretium ultricies penatibus. Facilisi natoque ultricies sapien ornare montes quis. Porta aliquet, ridiculus rhoncus varius magna congue volutpat litora et? Auctor integer neque turpis molestie mollis! Facilisis erat eget habitant suscipit, facilisi eget. Sociosqu conubia leo ullamcorper, rutrum sodales eu per. Habitant in per bibendum aptent maecenas euismod fames conubia vehicula. In senectus bibendum mollis imperdiet venenatis malesuada ligula tempor curabitur. Nascetur metus aptent parturient conubia! Vel morbi hendrerit eget rutrum amet per. Semper ullamcorper.'},
      {id: "input-auto-completion", title: 'Input Auto Completion', type: 'data-entry', image: 'patterns/ifml5.png', description: 'Semper vitae litora quis est dui potenti nisi vel. Faucibus nisl sagittis ac mauris id ullamcorper vel morbi nec ridiculus litora sodales. Velit pretium ultricies penatibus. Facilisi natoque ultricies sapien ornare montes quis. Porta aliquet, ridiculus rhoncus varius magna congue volutpat litora et? Auctor integer neque turpis molestie mollis! Facilisis erat eget habitant suscipit, facilisi eget. Sociosqu conubia leo ullamcorper, rutrum sodales eu per. Habitant in per bibendum aptent maecenas euismod fames conubia vehicula. In senectus bibendum mollis imperdiet venenatis malesuada ligula tempor curabitur. Nascetur metus aptent parturient conubia! Vel morbi hendrerit eget rutrum amet per. Semper ullamcorper.'},
      {id: "in-place-editing", title: 'In Place Editing', type: 'data-entry', image: 'patterns/ifml6.png', description: 'Semper vitae litora quis est dui potenti nisi vel. Faucibus nisl sagittis ac mauris id ullamcorper vel morbi nec ridiculus litora sodales. Velit pretium ultricies penatibus. Facilisi natoque ultricies sapien ornare montes quis. Porta aliquet, ridiculus rhoncus varius magna congue volutpat litora et? Auctor integer neque turpis molestie mollis! Facilisis erat eget habitant suscipit, facilisi eget. Sociosqu conubia leo ullamcorper, rutrum sodales eu per. Habitant in per bibendum aptent maecenas euismod fames conubia vehicula. In senectus bibendum mollis imperdiet venenatis malesuada ligula tempor curabitur. Nascetur metus aptent parturient conubia! Vel morbi hendrerit eget rutrum amet per. Semper ullamcorper.'},
    ]
  },
  {
    category: "Identification Authorization",
    list: [
      {id: "log-in", title: 'Log In', type: 'identification-authorization', image: 'patterns/ifml4.png', description: 'Semper vitae litora quis est dui potenti nisi vel. Faucibus nisl sagittis ac mauris id ullamcorper vel morbi nec ridiculus litora sodales. Velit pretium ultricies penatibus. Facilisi natoque ultricies sapien ornare montes quis. Porta aliquet, ridiculus rhoncus varius magna congue volutpat litora et? Auctor integer neque turpis molestie mollis! Facilisis erat eget habitant suscipit, facilisi eget. Sociosqu conubia leo ullamcorper, rutrum sodales eu per. Habitant in per bibendum aptent maecenas euismod fames conubia vehicula. In senectus bibendum mollis imperdiet venenatis malesuada ligula tempor curabitur. Nascetur metus aptent parturient conubia! Vel morbi hendrerit eget rutrum amet per. Semper ullamcorper.'},
      {id: "log-out", title: 'Log Out', type: 'identification-authorization', image: 'patterns/ifml5.png', description: 'Semper vitae litora quis est dui potenti nisi vel. Faucibus nisl sagittis ac mauris id ullamcorper vel morbi nec ridiculus litora sodales. Velit pretium ultricies penatibus. Facilisi natoque ultricies sapien ornare montes quis. Porta aliquet, ridiculus rhoncus varius magna congue volutpat litora et? Auctor integer neque turpis molestie mollis! Facilisis erat eget habitant suscipit, facilisi eget. Sociosqu conubia leo ullamcorper, rutrum sodales eu per. Habitant in per bibendum aptent maecenas euismod fames conubia vehicula. In senectus bibendum mollis imperdiet venenatis malesuada ligula tempor curabitur. Nascetur metus aptent parturient conubia! Vel morbi hendrerit eget rutrum amet per. Semper ullamcorper.'},
      {id: "in-place-sign-in", title: 'In Place Sign In', type: 'identification-authorization', image: 'patterns/ifml8-multi-page.png', description: 'Semper vitae litora quis est dui potenti nisi vel. Faucibus nisl sagittis ac mauris id ullamcorper vel morbi nec ridiculus litora sodales. Velit pretium ultricies penatibus. Facilisi natoque ultricies sapien ornare montes quis. Porta aliquet, ridiculus rhoncus varius magna congue volutpat litora et? Auctor integer neque turpis molestie mollis! Facilisis erat eget habitant suscipit, facilisi eget. Sociosqu conubia leo ullamcorper, rutrum sodales eu per. Habitant in per bibendum aptent maecenas euismod fames conubia vehicula. In senectus bibendum mollis imperdiet venenatis malesuada ligula tempor curabitur. Nascetur metus aptent parturient conubia! Vel morbi hendrerit eget rutrum amet per. Semper ullamcorper.'},
    ]
  }
];
